We deal wit Numpy package 
python is a dynamically typed 

numpy ----> base layer is C (whatever you are using the list, arrays those are c LANG DATA STRCUTRES )

reshape--> convert array to diamentioend matrix
shape --> will show the array diamention
arange ( )--> for array like range


In [1]:
import sys
print(sys.executable)

c:\Users\vinod\AppData\Local\Programs\Python\Python313\python.exe


In [2]:
! {sys.executable} -m pip install numpy

In [7]:
%pip install numpy
 #its a magic command --> % 
# %% two magic lines multi level commands
import os
os._exit(00)


: 

In [2]:
list1=[1,2,3]
list1 * 2 # duplciate the  existing the list 
import numpy as np
arr1=np.array(list1)
arr1*2


array([2, 4, 6])

In [5]:
type(arr1)

numpy.ndarray

In [7]:
type(arr1.shape)

tuple

In [10]:
arr2=np.arange(1,4)
arr2

arr3=np.arange(1,4,.5)
arr3

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [26]:
arr4=np.array([1,2.7,3.7,4.0],dtype="int")
# converting integer to floating internally 
# bcz of internal C lang 
arr4

arr6=np.array([0,10,100])

arr6 ** 10

array([                  0,         10000000000, 7766279631452241920])

In [34]:
m2=np.arange(1,13)
m2=m2.reshape(3,4) # assiingig to respective variable.
m2.shape

(3, 4)

In [6]:
import numpy as np
np.zeros(3,dtype="int")## creating the array with zeros like 3 variables.

np.zeros((2,3))

np.ones((2,3))## creating the array with onces like 3 variables.
np.diag([1,2,3])  # creating diagnolist matrix with 1 2 3 

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [7]:
np.identity(3) ## check the output of the matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
m1=np.arange(12).reshape(3,4)
print(m1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


: 

In [15]:
m1[1,1]
m1[0,1:3]

array([1, 2])

In [2]:
import numpy as np
m1=np.arange(12).reshape(3,4)
print(m1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
m1[1,1:3]

array([5, 6])

In [6]:
m1[1:1,1:3]
m1*4

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [8]:
m1[m1<6] ## where the is a true value that value will print here 
## like m1<6 means print the true and false values 


array([0, 1, 2, 3, 4, 5])

In [9]:
m1<6


array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In the above ones we are using Map and filter and reduce methods internally 
corss check once properly 


In [12]:
m1[m1%2==0].reshape(2,3)

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [14]:
a=np.array([1,2,3])
b=np.array([1,2,3])
a+b

# result is single diamension 


array([2, 4, 6])

*****************one diamesion is vector************************
**************************two diamension is matrix************************
three diamension is Tensor

In [15]:
a*b

array([1, 4, 9])

In [18]:
A= np.arange(12)

B=np.arange(12)
A*B

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [25]:
A.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
A.reshape(4,3)
B.reshape(3,4)
A*B

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [33]:
M2=np.mat(A,B)

AttributeError: `np.mat` was removed in the NumPy 2.0 release. Use `np.asmatrix` instead.

NameError: name 'A' is not defined

In [6]:
m1=np.arange(16).reshape(4,4)

In [7]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
m1[m1%2==0].reshape(2,4)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [13]:
a=np.array([1,2,3,4,5,6])
b=np.array([1,2,3,4,5,6])
a+b

## this is called vector bcz of single diamension 

array([ 2,  4,  6,  8, 10, 12])

In [15]:
A= np.arange(12).reshape(3,4)
B= np.arange(12).reshape(4,3)

In [17]:
A * B## diamensions shoul be same. 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[17], line 1
----> 1 A * B## diamensions shoul be same. 

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 
# but we can fix this as folows


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [28]:
A= np.arange(12).reshape(3,4)
B= np.arange(12).reshape(3,4)
A
B
A * B

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [24]:
A= np.arange(12).reshape(3,4)
B= np.arange(12).reshape(4,3)
np.matmul(A,B)


array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [23]:
A @ B

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [25]:
B@A

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [27]:
np.dot(A,B)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

************************Combination on Vectors and Matrixs****************** 

In [30]:
A= np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [32]:
A * a

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [33]:
np.dot(A,a)

ValueError: shapes (3,4) and (3,) not aligned: 4 (dim 1) != 3 (dim 0)

In [44]:
B=np.matmul(a,A)
B.reshape(1,4)

array([[32, 38, 44, 50]])

In [35]:
A @ a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [36]:
A + a

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [39]:
np.dot(a,A)

array([32, 38, 44, 50])